ALTER TABLE events ADD COLUMN IF NOT EXISTS step_personal BOOLEAN DEFAULT true;
ALTER TABLE events ADD COLUMN IF NOT EXISTS step_christian_life BOOLEAN DEFAULT true;
ALTER TABLE events ADD COLUMN IF NOT EXISTS step_health BOOLEAN DEFAULT true;
ALTER TABLE events ADD COLUMN IF NOT EXISTS step_emergency BOOLEAN DEFAULT true;
